import streamlit as st
import os

# --- PAGE CONFIGURATION ---
st.set_page_config(
    page_title="Master Quant Scanner",
    page_icon="📈",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- CACHE CLEARING FUNCTION ---
@st.cache_data(ttl=60)
def load_report(filepath):
    """Reads the markdown report from the local file system."""
    if os.path.exists(filepath):
        with open(filepath, "r", encoding="utf-8") as file:
            return file.read()
    else:
        return f"⚠️ **Report not found:** `{filepath}`\nThe master scanner may not have generated this file yet, or no setups cleared the institutional gates today."

# --- SIDEBAR ---
with st.sidebar:
    st.title("⚙️ Control Panel")
    st.write("Institutional Quant Scanner Dashboard.")
    
    # Instant manual refresh button
    if st.button("🔄 Refresh Data Instantly"):
        st.cache_data.clear()
        st.rerun()

    st.markdown("---")
    st.markdown("""
    **System Architecture:**
    - 1200+ Master Universe (Large/Mid/Small)
    - Explicit Options (F&O) Filter
    - Auto Position Sizing (₹50k Base)
    - ⭐ 2x Conviction Sizing (₹1L)
    - 250k Vol Liquidity & VWAP Gates
    - Strict 1:1.6 RRR Minimum
    """)

# --- MAIN DASHBOARD AREA ---
st.title("🚀 Master Quant Scanner Terminal")
st.write("Live institutional breakouts, squeeze blasts, and momentum setups.")

# Load the markdown files
intraday_data = load_report("intraday_report.md")
btst_data = load_report("btst_report.md")
swing_data = load_report("swing_report.md")

# Create navigation tabs
tab1, tab2, tab3 = st.tabs(["⚡ Intraday Scalps", "🌙 BTST Setups", "📈 Swing Trades"])

with tab1:
    st.markdown(intraday_data, unsafe_allow_html=True)

with tab2:
    st.markdown(btst_data, unsafe_allow_html=True)

with tab3:
    st.markdown(swing_data, unsafe_allow_html=True)

# --- FOOTER ---
st.markdown("---")
st.caption("Data generated by the automated GitHub Actions Master Scanner. Auto-refreshes every 60 seconds.")
